# Generated by Django 4.0 on 2021-12-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('date_naissance', models.DateField()),
                ('mail', models.CharField(max_length=70)),
                ('photo', models.ImageField(upload_to='')),
                ('etat', models.CharField(choices=[('C', 'Celibataire'), ('M', 'Marie'), ('D', 'Divorce'), ('V', 'Veuf')], default='C', max_length=1)),
                ('situation', models.CharField(choices=[('S', 'Sursitaire'), ('N', 'Non Concerne'), ('E', 'Exempte'), ('A', 'Accompli')], max_length=1)),
            ],
        ),
    ]
