# Generated by Django 4.0 on 2021-12-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='etat',
            field=models.CharField(choices=[('P', 'Présent'), ('A', 'Abscent'), ('R', 'Retard'), ('E', 'Exclu')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='situation',
            field=models.CharField(choices=[('N', 'Nouveau'), ('R', 'Redoublant'), ('D', 'Derogataire'), ('A', 'Autre')], max_length=1),
        ),
    ]
