# Generated by Django 4.0 on 2021-12-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_absence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(default='En ligne', max_length=10)),
                ('objectif', models.CharField(max_length=50)),
                ('resume', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('E', 'En cours'), ('T', 'Terminée'), ('A', 'Annulée'), ('D', 'Différée')], max_length=1)),
                ('type', models.CharField(choices=[('N', 'Normale'), ('R', 'Ratrapage'), ('S', 'Soutien'), ('F', 'Formation')], max_length=1)),
                ('absence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.absence')),
            ],
        ),
    ]
