# Generated by Django 4.0 on 2021-12-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_seance'),
    ]

    operations = [
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('nb_total_heure', models.IntegerField(max_length=3)),
                ('type', models.CharField(choices=[('Op', 'Optionnel'), ('Ob', 'Obligatoire')], max_length=2)),
                ('niveau', models.CharField(choices=[('L1', '1 er License'), ('L2', '2 éme License'), ('L3', '3 éme License'), ('M1', '1 er Mastére'), ('M2', '2 éme Mastére')], max_length=2)),
            ],
        ),
    ]
