# Generated by Django 4.0 on 2021-12-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='nb_total_heure',
            field=models.IntegerField(),
        ),
    ]
