# Generated by Django 4.0 on 2021-12-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_module_seance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('contenu', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('mp4', 'mp4'), ('flv', 'flv'), ('mov', 'mov'), ('avi', 'avi'), ('wmv', 'wmv')], max_length=4)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
