# Generated by Django 4.0 on 2021-12-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_enregistrement_seance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=8)),
                ('nb_etudiants', models.IntegerField()),
                ('mail', models.CharField(max_length=70)),
                ('niveau', models.CharField(choices=[('L1', '1 er License'), ('L2', '2 éme License'), ('L3', '3 éme License'), ('M1', '1 er Mastére'), ('M2', '2 éme Mastére')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app.groupe'),
            preserve_default=False,
        ),
    ]
