# Generated by Django 4.0 on 2021-12-13 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_travail_rendre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece_Jointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.etudiant')),
                ('travail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.travail_rendre')),
            ],
        ),
    ]
