# Generated by Django 4.0 on 2021-12-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_piece_jointe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('mail_personnelle', models.CharField(max_length=70)),
                ('mail_travail', models.CharField(max_length=70)),
                ('nb_heure', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='enseignant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app.enseignant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece_jointe',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.enseignant'),
        ),
    ]
