# Generated by Django 4.0 on 2021-12-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_enseignant_module_enseignant_piece_jointe_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='module',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='module_id', to='app.module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enseignant_id', to='app.enseignant'),
        ),
    ]
