# Generated by Django 4.0 on 2021-12-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_enseignant_module_alter_module_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='travail_rendre',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.enseignant'),
        ),
        migrations.AddField(
            model_name='travail_rendre',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.etudiant'),
        ),
    ]
