# Generated by Django 4.0 on 2021-12-15 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_travail_rendre_enseignant_travail_rendre_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece_jointe',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.enseignant'),
        ),
        migrations.AlterField(
            model_name='piece_jointe',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.etudiant'),
        ),
        migrations.AlterField(
            model_name='piece_jointe',
            name='travail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.travail_rendre'),
        ),
    ]
