from .etudiant import get_etudiants
from .etudiant import add_etudiant
from .etudiant import delete_etudiant
from .groupe import get_groupes
from .groupe import add_groupe
from .absence import get_absences
from .absence import add_absence
from .seance import get_seances
from .seance import add_seance
from .travail_rendre import get_travaux
from .travail_rendre import add_travail
from .piece_jointe import get_pieces
from .piece_jointe import add_piece
from .enseignant import get_enseignants
from .enseignant import add_enseignant
from .module import get_modules
from .module import add_module
from .enregistrement import get_enregistrements
from .enregistrement import add_enregistrement
